# $NetBSD$
#

DISTNAME=	tinderbox-dragonfly-${TBOX_VERSION}
CATEGORIES=	pkgtools
MASTERSITES=	http://tinderbox.marcuscom.com
EXTRACT_SUFX=	.tar.gz

MAINTAINER=	draco@marino.st
HOMEPAGE=	http://tinderbox/marcuscom.com
COMMENT=	Tinderbox package building system (pkgsrc)
LICENSE=	modified-bsd

TBOX_VERSION=		3.4.r1
PKG_DESTDIR_SUPPORT=	user-destdir	

.include "options.mk"

.include "../../mk/bsd.pkg.mk"
