#!/bin/sh

# usage: $0 DIRNAME PHASE ED PD FD BD RD TD [PLISTCHECK]
#   PHASE is 1 (checksum) or 2 (package)

cleanup() {
  status=$1

  if [ -e ${dir}/.keep ]; then
    cd ${dir}
    objdir=`bmake -V '\${WRKDIR}'`
    tar cfjC /tmp/work.tbz ${objdir}/.. work
  fi

  if [ ${status} -gt 0 ]; then
      cat /tmp/make.log${status}
  fi

  echo 1 > /tmp/status
  echo "================================================================"
  echo -n "build of ${dir} ended at "
  date

  exit 0
}

add_pkg() {
  pkgs=$*

  echo add_pkg $pkgs
  cd /tmp/depends
  export PKG_PATH=/tmp/depends
  if [ ! -z "${pkgs}" ]; then
    arch=$(uname -m)
    echo "adding dependencies"
    for i in $pkgs; do
      echo "pkg_add $i"
      base=$(basename $i .tgz)
      if pkg_info -q -e $base; then
        echo "skipping $base, already added"
      else
        if ! pkg_add $i; then
          echo "error in dependency $i, exiting"
          echo "1" > /tmp/status
          exit 1
        fi
      fi
    done
  fi
  # pkgsrc requires PKG_PATH variable be unset
  unset PKG_PATH
}

del_pkg() {
  pkgs=$*

  cd /tmp/depends
  export PKG_PATH=/tmp/depends
  if [ ! -z "${pkgs}" ]; then
    recursion=1
    dellist=""
    while [ $recursion -eq 1 ]; do
      unset delpkg nextpkg
      recursion=0
      for i in $pkgs; do
        base=$(basename $i .tgz)
        base=$(basename $base .tbz)
        if [ -s /var/db/pkg/${base}/+REQUIRED_BY ]; then
          recursion=1
          nextpkg="${base} ${nextpkg}"
        elif [ -d /var/db/pkg/${base}/ ]; then
          delpkg="${base} ${delpkg}"
        fi
      done
      pkgs="${nextpkg}"
      if [ "$dellist" != "" -a "$dellist" = "$delpkg" ]; then
        echo "deleted list =\""$dellist"\", packages to delete ="\"$delpkg\" #"
        echo "The following packages were left behind (perhaps your dependency list is incomplete):"
        ls /var/db/pkg
        echo "error in pkg_delete, exiting"
        cleanup 0
      else
        for j in ${delpkg}; do
          echo "Deleting ${j}"
          if ! (pkg_delete -f $j); then
            echo "--> error in pkg_delete, exiting"
            cleanup 0
          fi
        done
        dellist=$delpkg
      fi
    done
  fi
  find /var/db/pkg -type f -empty -delete
  # pkgsrc requires PKG_PATH variable be unset
  unset PKG_PATH
}

get_package_options() {
    # If the option file exists, it's stored in PKG_OPTIONS_FILE env var.
    # The format is ${DISTNAME}:jobs override:options list
    # example: gcc-4.6.1::-gcc-fortran
    #          In this example, there is no makejob override, fortran removed
    # example: gawk-3.1.8:1:portals
    #          In the above example, MAKE_JOBS=1, portals option added
    # Don't include any "nbX" suffixes, that is ${PKGNAME}.
    # Use the "DISTNAME" definition in the makefile.

    INFO_DISTNAME=$1
    MAKEJOBS_OVERRIDE=
    SPECIFIC_OPTIONS=
    if [ -z "${PKG_OPTIONS_FILE}" ]; then
	return
    fi

    instructions=`grep ${INFO_DISTNAME}: ${PKG_OPTIONS_FILE}`
    if [ -z "${instructions}" ]; then
	return
    fi

    test_override=`echo ${instructions} | awk 'BEGIN {FS=":"}; /^.+:[0-9]+:/ {print $2}'`
    if [ -n "{test_override}" ]; then
	MAKEJOBS_OVERRIDE="${test_override}"
    fi
    SPECIFIC_OPTIONS="`echo ${instructions} | awk 'BEGIN {FS=":"}; /^.+:[0-9]*:/ {print $3}'`"
}

dir=$1
phase=$2

ED=$3
PD=$4
FD=$5
BD=$6
RD=$7
TD=$8
PLISTCHECK=$9

L=$(echo ${LOCALBASE} | sed 's,^/,,')

export NO_PKGTOOLS_REQD_CHECK=1
export WRKOBJDIR=/work

cd $dir || exit 1

pkgname=`bmake -V '\${PKGNAME}'`
INFO_OPTVAR=`bmake -V '\${PKG_OPTIONS_VAR}'`
get_package_options `bmake -V '\${DISTNAME}'`

if [ $phase = 1 ]; then

  INFO_MAINTAINER=`bmake -V '\${MAINTAINER}'`
  INFO_PREFIX=`bmake -V '\${PREFIX}'`
  echo "build started at $(date)"
  echo "port directory: ${dir}"
  echo "building for:  $(uname -rm)"
  echo "maintained by: ${INFO_MAINTAINER}"
  echo "Makefile ident: $(ident ${dir}/Makefile | grep 'NetBSD:' | sed 's/^[ \t]*//')"
  echo "prefixes: LOCALBASE=${L} PREFIX=${INFO_PREFIX}"
  echo "Begin Configuration:"
  echo "---Begin Environment---"
  printenv | sort
  echo "---End Environment---"
  echo ""
  echo "---Begin OPTIONS List---"
  if [ -n "${INFO_OPTVAR}" -a -n "${SPECIFIC_OPTIONS}" ]; then
      bmake show-options ${INFO_OPTVAR}="${SPECIFIC_OPTIONS}"
  else
      bmake show-options
  fi
  echo "---End OPTIONS List---"
  echo ""
  echo "End Configuration."

  echo "FETCH_DEPENDS=${FD}"
  echo "PATCH_DEPENDS=${PD}"
  echo "EXTRACT_DEPENDS=${ED}"
  echo "BUILD_DEPENDS=${BD}"
  echo "RUN_DEPENDS=${RD}"
  echo "TEST_DEPENDS=${TD}"

  #Allow ports to notice they're being run in Tinderbox
  export PACKAGE_BUILDING=1

  # Stash a copy of /etc/master.passwd and /etc/group to detect whether someone modifies it
  cp /etc/master.passwd /etc/master.passwd-save
  cp /etc/group /etc/group-save

  # Files we do not care about changing between pre-build and post-cleanup
  cat > /tmp/mtree.preexclude <<EOF
./root/*
./var/*
./tmp/*
./etc/make.conf.bak
./etc/make.conf
./etc/periodic.conf
./etc/rc.conf
./work/*
./compat/linux/proc
./proc
./usr/share/man/cat*/*
./${L}/etc/apache
./${L}/news
./${L}/share/xml
./${L}/etc/gconf
./var/db/fontconfig
./distcache
EOF

  # Record a "pristine" mtree.
  mtree -X /tmp/mtree.preexclude -xcn -k uid,gid,mode -p / > /tmp/mtree.pristine

  add_pkg $FD

  cd $dir || exit 1

  echo "================================================================"
  echo "====================<phase 1: make checksum>===================="

  if /pnohang $TIMEOUT /tmp/make.log1 ${pkgname} bmake checksum; then
    cat /tmp/make.log1
    echo "0" > /tmp/status
  else
    cleanup 1
  fi

else

  echo "================================================================"
  echo "====================<phase 2: make extract>===================="

  add_pkg ${ED}
  
  # For an unfathomable reason, pkgsrc insists on bringing in build
  # dependencies in order to extract the files.  Not only is this
  # annoying if you want to check the contents of the tarball and you
  # have to build all the dependencies first, it means this script
  # has to be reordered where build dependencies come in very early.
  
  add_pkg ${BD}

  cd $dir
  # The config options need to come here because make extract pulls in 
  # make configure first, which is where this input is needed.
  if [ -n "${INFO_OPTVAR}" -a -n "${SPECIFIC_OPTIONS}" ]; then
      /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} bmake extract ${INFO_OPTVAR}="${SPECIFIC_OPTIONS}" || cleanup 2
  else
      /pnohang $TIMEOUT /tmp/make.log2 ${pkgname} bmake extract || cleanup 2
  fi
  cat /tmp/make.log2
  del_pkg ${ED}

  echo "================================================================"
  echo "====================<phase 3: make patch>===================="
  add_pkg ${PD}
  cd $dir
  /pnohang $TIMEOUT /tmp/make.log3 ${pkgname} bmake patch || cleanup 3
  cat /tmp/make.log3
  del_pkg ${PD}

  echo "================================================================"
  echo "====================<phase 4: make build>===================="

  # Files we do not care about changing between pre-build and post-cleanup
  cat > /tmp/mtree.buildexclude <<EOF
./var/log/*
./tmp/*
./work/*
./compat/linux/proc
./proc
./root/*
./var/mail/*
./var/tmp/*
./usr/share/man/cat*/*
./${L}/etc/apache
./${L}/news
./${L}/share/xml
./${L}/etc/gconf
./var/db/fontconfig
EOF
  # Record a "pristine" mtree.
  mtree -X /tmp/mtree.buildexclude -xcn -k uid,gid,mode -p / > /tmp/mtree.prebuild

  xvfb=0
  if which -s Xvfb; then
    xvfb=1
    pid=$(echo $$ % 32768 | bc)
    X11BASE=$(which Xvfb | sed -e 's./bin/Xvfb..')
    Xvfb :${pid} -fp ${X11BASE}/lib/X11/fonts/misc &
    DISPLAY=:${pid}
    export DISPLAY
  fi

  cd $dir
  portdir=$(echo ${dir} | sed -e 's|^/usr/pkg/||' -e 'y/\//_/')

  if [ -f .sleepme ]; then
      set > /tmp/.set_${portdir}
      touch /tmp/.sleep_${portdir}
      while [ -f /tmp/.sleep_${portdir} ]; do
	  echo "Sleeping for 60 seconds."
	  sleep 60
      done
      rm -f /tmp/.set_${portdir}
  fi

  # MAKE_JOBS normally defined in $LOCALBASE/etc/mk.conf, but it's
  # inside the tarball.  By default it's not set, so we override it here.
  # We can use the options file to specify exactly the number of jobs we want

  if [ -n "${MAKEJOBS_OVERRIDE}" ]; then
	echo "=> Number jobs set to ${MAKEJOBS_OVERRIDE} in options file"
	PORT_JOBS="MAKE_JOBS=${MAKEJOBS_OVERRIDE}"
  else
	ncpus=$(/sbin/sysctl hw.ncpu | awk '{print $2}')
	if [ "${npcus}" = "1" ]; then
		echo "=> Single job, only 1 CPU"
		PORT_JOBS="MAKE_JOBS=1"
	else
		factor=$(echo "$ncpus*2+1" | /usr/bin/bc)
		echo "=> Multiple CPUs: ${factor} jobs set"
		PORT_JOBS="MAKE_JOBS=${factor}"
	fi
  fi

  /pnohang $TIMEOUT /tmp/make.log4 ${pkgname} bmake build ${PORT_JOBS} || cleanup 4
  cat /tmp/make.log4

  echo "================================================================"
  echo "====================<phase 5: make test>===================="

  echo "Pkgsrc does not have per-package regression test capability, skipped."

  echo "================================================================"
  echo "====================<phase 6: make install>===================="

  add_pkg ${RD}

  cat > /tmp/mtree.exclude <<EOF
./root/*
./var/*
./tmp/*
./etc/make.conf.bak
./etc/make.conf
./etc/periodic.conf
./etc/rc.conf
./work/*
./compat/linux/proc
./proc
EOF
  mtree -X /tmp/mtree.exclude -xcn -k uid,gid,mode -p / > /tmp/mtree

  cd $dir
  if /pnohang $TIMEOUT /tmp/make.log6 ${pkgname} bmake install; then
    cat /tmp/make.log6
    echo "0" > /tmp/status
  else
    cleanup 6
  fi

  echo "================================================================"
  echo "====================<phase 7: make package>===================="
  cd $dir
  if /pnohang $TIMEOUT /tmp/make.log7 ${pkgname} bmake package; then
      echo "0" > /tmp/status
  else
      echo "1" > /tmp/status
  fi

  cat /tmp/make.log7
  prefix=`bmake -V '\${PREFIX}'`
  du -skx / | awk '{print $1}' > /tmp/size
  del_pkg ${pkgname}


  mtree -X /tmp/mtree.exclude -x -f /tmp/mtree -p / | egrep -v "^(${L}/var|${L}/lib/X11/xserver/SecurityPolicy|${L}/share/nls/POSIX|${L}/share/nls/en_US.US-ASCII|etc/services|compat |${L} |etc/manpath.config|etc/.*.bak|${L}/info/dir|${L}/lib/X11/fonts/.*/fonts\.|${L}/man/..( |/man. )|${L}/lib/X11/fonts/TrueType|${L}/etc/gconf/gconf.xml.defaults/%gconf-tree.*.xml|var/db/fontconfig/*|usr/X11R6 )" > /tmp/list3

  dirty=0
  if [ -s /tmp/list3 ]; then
    cd /
    grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
    grep ' missing$' /tmp/list3 > /tmp/list5
    grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
    if [ -n "${PLISTCHECK}" ]; then
      if grep -vqE "(${L})/etc/" /tmp/list4; then
        echo "1" > /tmp/status
        dirty=1
      fi
      if [ -s /tmp/list5 -o -s /tmp/list6 ]; then
        echo "1" > /tmp/status
        dirty=1
      fi
    fi
      echo "================================================================"
  fi

  echo
  echo "=== Deleting /var/db/pkg/pkgdb.byfile.db"
  rm -f /var/db/pkg/pkgdb.byfile.db

  echo "=== Checking filesystem state"

  if [ -s /tmp/list4 ]; then
    echo "list of extra files and directories in / (not present before this port was installed but present after it was deinstalled)"
    cat /tmp/list4
    touch /tmp/leftovers
  fi
  if [ -s /tmp/list5 ]; then
    echo "list of files present before this port was installed but missing after it was deinstalled)"
    cat /tmp/list5
    touch /tmp/leftovers
  fi
  if [ -s /tmp/list6 ]; then
    echo "list of filesystem changes from before and after port installation and deinstallation"
    cat /tmp/list6
    touch /tmp/leftovers
  fi
  if [ "${dirty}" = 1 ]; then
    cleanup 0
  fi

  # BUILD_DEPENDS need to be present at install-time, e.g. gmake
  # FETCH_DEPENDS contains the digests which is needed throught the process
  # Concatenate and remove duplicates
  BRFD=$(echo $BD $RD $FD | tr ' ' '\n' | sort -u | tr '\n' ' ')
  del_pkg ${BRFD}
  cd /var/db/pkg
  if [ $(echo $(echo * | wc -c)) != 2 ]; then
    echo "leftover packages:" *
    del_pkg *
    echo "1" > /tmp/status
    cleanup 0
  fi

  # Compare the state of the filesystem now to clean system (should again be clean)
  mtree -X /tmp/mtree.preexclude -x -f /tmp/mtree.pristine -p / | egrep -v "^(${L}/var|${L}/lib/X11/xserver/SecurityPolicy|${L}/share/nls/POSIX|${L}/share/nls/en_US.US-ASCII|etc/services|compat |${L} |etc/manpath.config|etc/.*.bak|${L}/info/dir|${L}/lib/X11/fonts/.*/fonts\.|${L}/man/..( |/man. )|${L}/lib/X11/fonts/TrueType|${L}/etc/gconf/gconf.xml.defaults/%gconf-tree.*.xml|var/db/fontconfig/*|usr/X11R6 )" > /tmp/list3
  echo
  echo "=== Checking filesystem state after all packages deleted"

  if [ -s /tmp/list3 ]; then
      cd /
      grep ' extra$' /tmp/list3 | awk '{print $1}' | xargs -J % find % -ls > /tmp/list4
      grep ' missing$' /tmp/list3 > /tmp/list5
      grep -vE ' (extra|missing)$' /tmp/list3 > /tmp/list6
      if [ -n "${PLISTCHECK}" ]; then
	  if grep -vqE "(${L})/etc/" /tmp/list4; then
	      #echo "1" > /tmp/status
	  fi
	  if [ -s /tmp/list5 ]; then
	      #echo "1" > /tmp/status
	  fi
      fi
      echo "================================================================"

      if [ -s /tmp/list4 ]; then
	  echo "list of extra files and directories in / (not present on clean system but present after everything was deinstalled)"
	  cat /tmp/list4
	  touch /tmp/leftovers
      fi
      if [ -s /tmp/list5 ]; then
	  echo "list of files present on clean system but missing after everything was deinstalled)"
	  cat /tmp/list5
	  touch /tmp/leftovers
      fi
      if [ -s /tmp/list6 ]; then
	  echo "list of filesystem changes from before and after all port installation/deinstallation"
	  cat /tmp/list6
	  touch /tmp/leftovers
      fi
  fi

  cmp /etc/group /etc/group-save || (echo "=== /etc/group was modified:"; diff -du /etc/group-save /etc/group)
  cmp /etc/master.passwd /etc/master.passwd-save || (echo "=== /etc/master.passwd was modified:"; diff -du /etc/master.passwd-save /etc/master.passwd)

  if [ ${xvfb} = 1 ]; then
    kill $(jobid %1)
  fi

  if [ -e ${dir}/.keep ]; then
    cd ${dir}
    objdir=`bmake -V '\${WRKDIR}'`
    tar cfjC /tmp/work.tbz ${objdir}/.. work
  fi

  echo "================================================================"
  echo -n "build of ${dir} ended at "
  date

fi

exit 0
